import type { Metadata } from "next";
import "./global.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex flex-col min-h-screen">
        <header className="h-16 border-b gap-4 px-6 flex items-center border-gray-300">
          <Button asChild variant="ghost" className="font-bold text-xl">
            <Link href="/">
              ヘッダー
            </Link>
          </Button>
          <Button asChild variant="ghost" className="font-bold text-xl">
            <Link href="/about">
              このサービスについて
            </Link>
          </Button>
        </header>
        {children}
        <footer className="h-16 px-6 flex items-center sticky top-full border-t border-gray-300">
          <h1>フッター</h1>
        </footer>
      </body>
    </html>
  );
}
